Initial implementation of download-behavior.
MaritzSTL/mtz-file-download-behavior pull request #1
Opened 2017-07-21 16:11 UTC by haydenmcp

- Implemented behavior.
- Implemented demo.
- Implemented tests.

2017-07-21 22:42 UTC, stramel requested changes

2017-07-21 22:42 UTC, stramel commented on demo/index.html
> +                    const data = "You've serialized data to file. Happy days!!!";
I would use `iron-ajax` to fetch a `csv` from this repository and use the same `csv` in the `downloadFromURI`

2017-07-21 22:42 UTC, stramel commented on mtz-file-download-behavior.html
> +     * @param {string} data - data to encode.
Use javascript primitives. `String` instead of `string`

2017-07-21 22:42 UTC, stramel commented on mtz-file-download-behavior.html
> +     * @param {string} uri - The uri to open.
Use primitives here as well

2017-07-21 22:42 UTC, stramel commented on test/mtz-file-download-behavior_test.html
> +              const data = "You've serialized data to file. Happy days!!!";
Use csv instead of plain text. csv is our common usecase

2017-07-21 22:42 UTC, stramel commented on test/mtz-file-download-behavior_test.html
> +              // debugger;
Remove debugging code.

2017-07-23 17:54 UTC, haydenmcp commented on mtz-file-download-behavior.html
> +     * @param {string} data - data to encode.
[ ] make change

2017-07-23 17:55 UTC, haydenmcp commented on test/mtz-file-download-behavior_test.html
> +              const data = "You've serialized data to file. Happy days!!!";
- [ ] use csv

2017-07-23 17:55 UTC, haydenmcp commented on test/mtz-file-download-behavior_test.html
> +              // debugger;
- [ ] remove debug comment

2017-07-23 18:29 UTC, haydenmcp commented on test/mtz-file-download-behavior_test.html
> +              const data = "You've serialized data to file. Happy days!!!";
I'm encountering an issue with CORS related to opening the csv in the same window as that of the demo. Any recommendations on how to circumvent that issue?

2017-07-24 14:59 UTC, stramel commented on test/mtz-file-download-behavior_test.html
> +              const data = "You've serialized data to file. Happy days!!!";
I wouldn't worry about that right now. Generally, I think they are going to want it to open in a new window anyways.

2017-07-24 15:08 UTC, stramel requested changes

2017-07-24 15:08 UTC, stramel commented on bower.json
> +    "app-localize-behavior": "PolymerElements/app-localize-behavior#^1.0 || 2.0"
Remove app-localize-behavior

2017-07-24 15:08 UTC, stramel commented on mtz-file-download-behavior.html
> +  const mtz = window.mtz || {};
`window.mtz = window.mtz || {};`

2017-07-24 15:08 UTC, stramel commented on mtz-file-download-behavior.html
> +    downloadFromURI(uri, newTab) {
default to newTab `newTab = '_blank';` 
also update docs

2017-07-24 15:08 UTC, stramel commented on mtz-file-download-behavior.html
> +    downloadFromData(data, type, name) {
provide a defaulted `name` maybe something generic like `download`

2017-07-24 15:08 UTC, stramel commented on test/mtz-file-download-behavior_test.html
> +              this.downloadFromURI('./sample.txt', true);
sample.txt was removed make sure to update these tests.

2017-07-24 15:43 UTC, stramel commented on demo/index.html
> +                    this.downloadFromURI('https://github.com/MaritzSTL/mtz-file-download-behavior/tree/master/demo/sample.csv', true);
use a local reference here instead.

Aslo push a csv file for it to point to.

2017-07-24 15:50 UTC, haydenmcp commented on demo/index.html
> +                    this.downloadFromURI('https://github.com/MaritzSTL/mtz-file-download-behavior/tree/master/demo/sample.csv', true);
I'm a bit confused. When you say a local reference, what are you referring to in this context?

2017-07-24 15:57 UTC, stramel commented on demo/index.html
> +                    this.downloadFromURI('https://github.com/MaritzSTL/mtz-file-download-behavior/tree/master/demo/sample.csv', true);
`demo/sample.csv`

2017-07-24 16:04 UTC, haydenmcp commented on demo/index.html
> +                    this.downloadFromURI('https://github.com/MaritzSTL/mtz-file-download-behavior/tree/master/demo/sample.csv', true);
- [ ] Impl

2017-07-24 16:31 UTC, stramel submitted a review, later dismissed

2017-07-24 16:59 UTC, stramel submitted a review, later dismissed
LTGM pending Green build

2017-07-24 19:16 UTC, admwx7 requested changes

2017-07-24 19:16 UTC, admwx7 commented on mtz-file-download-behavior.html
> +        document.body.appendChild(link);
Do we need to appendChild here?

2017-07-24 19:16 UTC, admwx7 commented on mtz-file-download-behavior.html
> +     * @returns {Boolean} Returns true.
`@return`

2017-07-24 19:16 UTC, admwx7 commented on test/mtz-file-download-behavior_test.html
> +      <template>
Doesn't look like you're using this template anywhere, just drop it instead.

2017-07-24 19:22 UTC, haydenmcp commented on mtz-file-download-behavior.html
> +        document.body.appendChild(link);
Looks like we don't so I've removed it

2017-07-24 19:27 UTC, stramel submitted a review, later dismissed
Pending ✔️

2017-07-25 02:49 UTC, stramel submitted a review, later dismissed

2017-07-25 14:53 UTC, admwx7 approved these changes

2017-07-25 19:12 UTC, stramel approved these changes

2017-07-25 19:13 UTC, merged